## The class Perceptron

The class Perceptron implements a single\-layer perceptron with $n$ inputs. This class provides the following public functions: 

- predict\(inputs\) calculates the weighted sum of the inputs and applies the step function to calculate the output.

- fit\(inputs, labels, learning\_rate, epochs\) fits the model by updating the weights and the bias considering the learning rate and the error of the prediction. The training inputs define the input patterns and the labels define the expected outputs, the training is run up to the given epochs \(iterations\).

- predictions\(inputs, labels\) returns a list with the model predictions.

- evaluate\(input, labels, function\) evaluates the accuracy of the model.

The perceptron is a linear classifier and can "learn" linearly separable functions.

In [166]:
import numpy as np

class Perceptron:
    def __init__(self, total_inputs):
        # the weights and the bias are initialized to zeros

        self.__weights = np.zeros(total_inputs)
        self.__bias = 0

    def __step(self, x):
        # the activation function is a step function: 1 if x > 0 and 0 otherwise

        return 1 if x > 0 else 0

    @property
    def weights(self):
        return self.__weights

    @property
    def bias(self):
        return self.__bias

    def predict(self, inputs):
        # the prediction is calculated as the dot product of the weights and the inputs plus the bias

        activation = np.dot(self.__weights.T, np.array(inputs)) + self.__bias

        return self.__step(activation)

    def fit(self, inputs, labels, learning_rate, epochs):
        #the perceptron is trained by trail and error, adjusting the weights and the bias each iteration (epoch)

        self.__inputs = np.array(inputs)
        self.__labels = np.array(labels)

        for epoch in range(epochs):
            for inputs, label in zip(self.__inputs, self.__labels):
                prediction = self.predict(inputs)

                #update weights and the bias considering the learning rate
                #and the error of the prediction (label - prediction)

                self.__weights += self.__weights + learning_rate * (label - prediction) * inputs
                self.__bias += learning_rate * (label - prediction)

    def predictions(self, inputs, labels):
        output = []

        for input, label in zip(inputs, labels):
            prediction = self.predict(input)
            
            output.append(prediction)

        return output

    
    def evaluate(self, function):
        print (f"{function} \n")

        correct_predictions = 0

        for input, label in zip(self.__inputs, self.__labels):
            prediction = self.predict(input)

            if prediction == label:
                correct_predictions+=1

            print (f"{input} {prediction}")

        print (f"\nAccuracy {(correct_predictions/len(inputs)) * 100}%\n")       

In [167]:
# MAX_EPOCHS = 10

# inputs = [[0,0], [0,1], [1,0], [1,1]]

# or_perceptron = Perceptron(total_inputs=2)
# or_perceptron.fit(inputs, [0,1,1,1], 0.1, MAX_EPOCHS)

# or_perceptron.evaluate(inputs, [0,1,1,1,], "OR")

In [168]:

print("2-input logic functions learned by a single-layer perceptron using 100% of the inputs \n")

# 2-input logic functions OR, NOr, AND, NAND, Least Significant Bit, Most Significant Bit, and XOR

MAX_EPOCHS = 10

inputs = [[0, 0], [0, 1], [1, 0], [1, 1]]

# OR

or_perceptron = Perceptron(total_inputs=2)
or_perceptron.fit(inputs, [0, 1, 1, 1], learning_rate=0.1, epochs=MAX_EPOCHS)
or_perceptron.evaluate("2-input OR")

# NOR

nor_perceptron = Perceptron(total_inputs=2)
nor_perceptron.fit(inputs, [1, 0, 0, 0], learning_rate=0.1, epochs=MAX_EPOCHS)
nor_perceptron.evaluate("2-input NOR")

# AND

and_perceptron = Perceptron(total_inputs=2)
and_perceptron.fit(inputs, [0, 0, 0, 1], learning_rate=0.1, epochs=MAX_EPOCHS)
and_perceptron.evaluate("2-input AND")

# NAND

nand_perceptron = Perceptron(total_inputs=2)
nand_perceptron.fit(inputs, [1, 1, 1, 0], learning_rate=0.1, epochs=MAX_EPOCHS)
nand_perceptron.evaluate("2-input NAND")

# Least Significant Bit (lsb)

lsb_perceptron = Perceptron(total_inputs=2)
lsb_perceptron.fit(inputs, [0, 1, 0, 1], learning_rate=0.1, epochs=MAX_EPOCHS)
lsb_perceptron.evaluate("2-input Least Significant Bit")

# Most Significant Bit (msb)

msb_perceptron = Perceptron(total_inputs=2)
msb_perceptron.fit(inputs, [0, 0, 1, 1], learning_rate=0.1, epochs=MAX_EPOCHS)
msb_perceptron.evaluate("2-input Most Significant Bit")

# Can the Perceptron learn the XOR function? No, the XOR function is non-linearly separable

xor_perceptron = Perceptron(total_inputs=2)
xor_perceptron.fit(inputs, [0, 1, 1, 0], learning_rate=0.1, epochs=MAX_EPOCHS)
xor_perceptron.evaluate("2-input XOR")

2-input logic functions learned by a single-layer perceptron using 100% of the inputs 

2-input OR 

[0 0] 0
[0 1] 1
[1 0] 1
[1 1] 1

Accuracy 100.0%

2-input NOR 

[0 0] 1
[0 1] 0
[1 0] 0
[1 1] 0

Accuracy 100.0%

2-input AND 

[0 0] 0
[0 1] 1
[1 0] 1
[1 1] 1

Accuracy 50.0%

2-input NAND 

[0 0] 1
[0 1] 0
[1 0] 0
[1 1] 0

Accuracy 50.0%

2-input Least Significant Bit 

[0 0] 0
[0 1] 1
[1 0] 0
[1 1] 1

Accuracy 100.0%

2-input Most Significant Bit 

[0 0] 0
[0 1] 0
[1 0] 1
[1 1] 1

Accuracy 100.0%

2-input XOR 

[0 0] 0
[0 1] 1
[1 0] 0
[1 1] 1

Accuracy 50.0%



In [169]:
import random

print("Linearly separable function Majority learned by a single-layer perceptron using 100% of the inputs \n")

# 5-input majority function

MAX_EPOCHS = 20

inputs = [[0, 0, 0, 0, 0],
          [0, 0, 0, 0, 1],
          [0, 0, 0, 1, 0],
          [0, 0, 0, 1, 1],
          [0, 0, 1, 0, 0],
          [0, 0, 1, 0, 1],
          [0, 0, 1, 1, 0],
          [0, 0, 1, 1, 1],
          [0, 1, 0, 0, 0],
          [0, 1, 0, 0, 1],
          [0, 1, 0, 1, 0],
          [0, 1, 0, 1, 1],
          [0, 1, 1, 0, 0],
          [0, 1, 1, 0, 1],
          [0, 1, 1, 1, 0],
          [0, 1, 1, 1, 1],
          [1, 0, 0, 0, 0],
          [1, 0, 0, 0, 1],
          [1, 0, 0, 1, 0],
          [1, 0, 0, 1, 1],
          [1, 0, 1, 0, 0],
          [1, 0, 1, 0, 1],
          [1, 0, 1, 1, 0],
          [1, 0, 1, 1, 1],
          [1, 1, 0, 0, 0],
          [1, 1, 0, 0, 1],
          [1, 1, 0, 1, 0],
          [1, 1, 0, 1, 1],
          [1, 1, 1, 0, 0],
          [1, 1, 1, 0, 1],
          [1, 1, 1, 1, 0],
          [1, 1, 1, 1, 1]]

labels = [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1]

# test the perceptron using 100% of the inputs for training

majority_perceptron = Perceptron(total_inputs=5)
majority_perceptron.fit(inputs, labels, learning_rate=0.1, epochs=MAX_EPOCHS)
majority_perceptron.evaluate("5-input Majority function")





print("Linearly separable function Majority learned by a single-layer perceptron using 80% of the inputs \n")

# 5-input majority function using 80% of the inputs for training

input_data = []

# combine the inputs and labels into the input data

for evidence, label in zip(inputs, labels):
    input_data.append(evidence + [label])

# shuffle the input data with inputs and labels

random.shuffle(input_data)

# select 80% of the input data

data_size = int(0.8 * len(input_data))

selected_inputs = input_data[:data_size]

# split the combined inputs into two lists: training_inputs and training_labels

training_inputs = []
training_labels = []

for input_data in selected_inputs:
    training_inputs.append(input_data[:5])
    training_labels.append(input_data[5])

print("Training data \n")

for training_input in training_inputs:
    print(training_input)

print(" ")

# test the perceptron using 80% of the inputs for training

majority_perceptron_80 = Perceptron(total_inputs=5)
majority_perceptron_80.fit(training_inputs, training_labels, learning_rate=0.1, epochs=MAX_EPOCHS)
majority_perceptron_80.evaluate("5-input Majority function trained with 80% of random inputs")


Linearly separable function Majority learned by a single-layer perceptron using 100% of the inputs 

5-input Majority function 

[0 0 0 0 0] 0
[0 0 0 0 1] 1
[0 0 0 1 0] 1
[0 0 0 1 1] 1
[0 0 1 0 0] 1
[0 0 1 0 1] 1
[0 0 1 1 0] 1
[0 0 1 1 1] 1
[0 1 0 0 0] 0
[0 1 0 0 1] 0
[0 1 0 1 0] 1
[0 1 0 1 1] 1
[0 1 1 0 0] 1
[0 1 1 0 1] 1
[0 1 1 1 0] 1
[0 1 1 1 1] 1
[1 0 0 0 0] 0
[1 0 0 0 1] 1
[1 0 0 1 0] 1
[1 0 0 1 1] 1
[1 0 1 0 0] 1
[1 0 1 0 1] 1
[1 0 1 1 0] 1
[1 0 1 1 1] 1
[1 1 0 0 0] 0
[1 1 0 0 1] 0
[1 1 0 1 0] 1
[1 1 0 1 1] 1
[1 1 1 0 0] 1
[1 1 1 0 1] 1
[1 1 1 1 0] 1
[1 1 1 1 1] 1

Accuracy 62.5%

Linearly separable function Majority learned by a single-layer perceptron using 80% of the inputs 

Training data 

[1, 1, 1, 0, 0]
[0, 0, 0, 0, 1]
[0, 0, 1, 1, 1]
[0, 0, 0, 0, 0]
[1, 1, 1, 1, 0]
[1, 0, 0, 1, 1]
[1, 1, 0, 0, 1]
[1, 0, 1, 0, 1]
[0, 1, 0, 1, 0]
[0, 1, 1, 0, 0]
[0, 1, 1, 0, 1]
[0, 1, 1, 1, 1]
[0, 0, 1, 1, 0]
[1, 0, 1, 1, 0]
[1, 1, 1, 1, 1]
[0, 1, 1, 1, 0]
[0, 0, 1, 0, 0]
[1, 1, 0, 1, 1]
[1